import React, { createContext, useState, useEffect } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';

export const SUPPORTED_LANGUAGES = [
  { code: 'en', name: 'English', native: 'English', flag: '🇬🇧' },
  { code: 'hi', name: 'Hindi', native: 'हिन्दी', flag: '🇮🇳' },
  { code: 'te', name: 'Telugu', native: 'తెలుగు', flag: '🇮🇳' },
  { code: 'ta', name: 'Tamil', native: 'தமிழ்', flag: '🇮🇳' },
  { code: 'es', name: 'Spanish', native: 'Español', flag: '🇪🇸' },
  { code: 'fr', name: 'French', native: 'Français', flag: '🇫🇷' },
  { code: 'de', name: 'German', native: 'Deutsch', flag: '🇩🇪' },
  { code: 'ja', name: 'Japanese', native: '日本語', flag: '🇯🇵' },
  { code: 'ar', name: 'Arabic', native: 'العربية', flag: '🇸🇦' },
];

const TRANSLATIONS = {
  en: {
    // Brand & Navigation
    appName: 'NanoSafe Analyzer',
    appSub: 'Translational Nanomedicine & Cytotoxicity Platform',
    projectTitle: 'Evaluation of the Biocompatibility and Cytotoxicity of ZnO Nanoparticles to Determine Safe Biomedical Usage Levels',
    dashboard: 'Dashboard',
    newAnalysis: 'New Analysis',
    history: 'History',
    compare: 'Compare',
    patients: 'Patients',
    isoGuide: 'ISO Standards',
    profile: 'Profile',
    settings: 'Settings & Config',
    logout: 'Sign Out',
    changeLang: 'Change Language',
    selectLang: 'Select App Language',
    mlEngineActive: 'ML Toxicology Engine Active',
    welcomeBack: 'Welcome back,',
    quickModules: 'Quick Access Modules',
    sideBySide: 'Side-by-Side Datasets',
    pastRecords: 'Past Experiment Records',
    clinicalCohorts: 'Clinical Cohort Records',

    // Dashboard Stats
    totalExperiments: 'Total Analyses',
    activePatients: 'Active Patients',
    avgViability: 'Avg Viability',
    isoPassRate: 'ISO Pass Rate',
    recentActivity: 'Recent Clinical Assays',
    quickActions: 'Quick Actions',
    startNewAssay: 'Start New Assay',
    enrollPatient: 'Enroll Patient',
    viewAllRecords: 'View All History',

    // New Analysis Flow
    step1Patient: '1. Select Study Subject / Patient',
    step2Assay: '2. Assay Parameters & Cell Model',
    step3Dose: '3. Dose-Response Measurements (Optical Density)',
    sampleTitle: 'Evaluation / Sample Title',
    targetCellLine: 'Target Cell Line',
    exposureDuration: 'Exposure Duration',
    biomedicalApp: 'Biomedical Application Target',
    calcCytotoxicity: 'Run ISO 10993-5 Analysis',
    patientOptional: '👤 Patient / Subject',
    generalScreening: '🔬 Preclinical Material Screening (No Patient)',
    enterCustomTitle: 'Enter sample title...',
    evaluating: 'Running 4PL & ML Analysis...',
    concentration: 'Concentration (µg/mL)',
    opticalDensity: 'Optical Density (OD 570nm)',
    blankControl: 'Blank OD Control',
    negativeControl: 'Negative Control (100% Viable)',

    // Results & Risk Ratings
    analysisResult: 'Analysis Results',
    viabilityScore: 'Cell Viability',
    toxicityScore: 'Toxicity Score',
    riskLevel: 'Risk Level',
    safe: 'Safe / Biocompatible',
    moderate: 'Moderate Risk',
    toxic: 'High Risk (Cytotoxic)',
    ic50: 'Calculated IC50',
    conformance: 'ISO 10993-5 Conformance',
    isoPass: 'ISO 10993-5 Pass (Viability ≥ 70%)',
    isoFail: 'ISO 10993-5 Fail (Viability < 70%)',
    dosageSafe: 'Recommended Safe Dosage',
    reRunAssay: 'Re-Run Assay',
    saveToHistory: 'Save to Clinical History',

    // History Screen
    allRecords: 'All Records',
    patientAssays: 'Patients History',
    materialScreening: 'Material Screening',
    showingAllPatients: 'Showing: All Enrolled Patients',
    searchHistory: 'Search by patient, sample, or cell line...',
    filter: 'Filter',
    reset: 'Reset',
    noRecords: 'No experiment records found.',
    filterAll: 'All',
    filterSafe: 'Safe',
    filterModerate: 'Moderate',
    filterToxic: 'Toxic',
    dateAdded: 'Date Added',

    // Patients Screen
    patientRegistry: 'Clinical Study Registry',
    enrollNewPatient: 'Enroll New Patient',
    patientName: 'Full Patient Name',
    bloodGroup: 'Blood Group',
    cohort: 'Study Cohort / Group',
    consentStatus: 'Consent Status',
    consented: 'Consented',
    pending: 'Pending',
    totalAssaysCount: 'Assays Recorded',
    enrollBtn: 'Enroll Subject',
    patientId: 'Patient ID',
    ageYears: 'Age (Years)',
    gender: 'Sex / Gender',
    notes: 'Clinical Notes / Medical History',
    noPatientsFound: 'No patients enrolled yet.',

    // Compare Screen
    compareTitle: 'Multi-Dataset Comparison',
    compareSub: 'Compare dose-response curves and cytotoxicity metrics across trials',
    selectDatasetA: 'Select Dataset A',
    selectDatasetB: 'Select Dataset B',
    deltaComparison: 'Metric Differential (Δ)',
    viabilityDiff: 'Viability Difference',
    ic50Diff: 'IC50 Difference',

    // Clinical Standards Guide (ISO)
    isoStandardsTitle: 'ISO 10993-5 Biological Evaluation Guide',
    isoGuideSub: 'International standards for in vitro cytotoxicity evaluation of medical devices',
    grade0: 'Grade 0: None (Viability ≥ 100%)',
    grade1: 'Grade 1: Slight (Viability 80% - 99%)',
    grade2: 'Grade 2: Mild (Viability 70% - 79%)',
    grade3: 'Grade 3: Moderate (Viability 50% - 69%)',
    grade4: 'Grade 4: Severe (Viability < 50%)',
    isoPassThreshold: 'Pass Standard: Viability ≥ 70% of negative control',

    // Profile & First-time Setup
    researcherProfile: 'Researcher Profile',
    mandatoryInfo: '🔴 Mandatory Information',
    optionalInfo: '⚪ Optional Information',
    saveProfile: 'Save Researcher Profile',
    editProfile: 'Edit Profile',
    identityDetails: '👤 Identity & Personal Details',
    contactLocation: '📞 Contact & Location',
    labAffiliation: '🔬 Laboratory & Affiliation',
    personalBio: '📝 Personal Bio / About Me',
    fullName: 'Full Legal Name',
    titleSalutation: 'Title / Salutation',
    institution: 'Institution / Organization',
    researchRole: 'Research Role / Title',
    genderPronouns: 'Gender / Pronouns',
    dateOfBirth: 'Date of Birth / Age',
    primaryEmail: 'Primary Email',
    secondaryEmail: 'Alternative / Secondary Email',
    officeAddress: 'Office / Lab Address',
    cityState: 'City & State',
    country: 'Country',
    preferredLanguage: 'Preferred Language',
    bio: 'Bio / Research Summary',
    notSet: 'Not set',
    verified: 'Verified',
    uploadPhoto: 'Upload Photo',
    changePhoto: 'Change Photo',
    takePhoto: 'Take Camera Photo',
    chooseGallery: 'Choose from Gallery',
    removePhoto: 'Remove Photo',
    cancel: 'Cancel',
    save: 'Save',
    edit: 'Edit',
    changePassword: 'Change Password',
    security: 'Security',
    currentPwd: 'Current Password',
    newPwd: 'New Password',
    confirmPwd: 'Confirm New Password',
    updatePassword: 'Update Password',

    // Auth
    signIn: 'Sign In',
    register: 'Create Account',
    username: 'Username',
    password: 'Password',
    email: 'Email Address',
    verifyOtp: 'Verify 6-Digit OTP',
    enterOtpCode: 'Enter verification code',
    verifyAndLogin: 'Verify & Access Workspace',
  },

  hi: {
    // Hindi (हिन्दी)
    appName: 'नैनोसेफ विश्लेषक',
    appSub: 'ट्रांसलेशनल नैनोमेडिसिन और साइटोटॉक्सिसिटी प्लेटफॉर्म',
    projectTitle: 'सुरक्षित बायोमेडिकल उपयोग स्तर निर्धारित करने के लिए ZnO नैनोकणों की बायोकंपैटिबिलिटी और साइटोटॉक्सिसिटी का मूल्यांकन',
    dashboard: 'डैशबोर्ड',
    newAnalysis: 'नया विश्लेषण',
    history: 'इतिहास',
    compare: 'तुलना करें',
    patients: 'मरीज / रोगी',
    isoGuide: 'आईएसओ मानक',
    profile: 'प्रोफ़ाइल',
    logout: 'लॉग आउट',
    changeLang: 'भाषा बदलें',
    selectLang: 'ऐप की भाषा चुनें',
    mlEngineActive: 'एमएल विषविज्ञान इंजन सक्रिय',
    welcomeBack: 'वापसी पर स्वागत है,',
    quickModules: 'त्वरित मॉड्यूल',
    sideBySide: 'डेटासेट तुलना',
    pastRecords: 'पिछले प्रयोग रिकॉर्ड',
    clinicalCohorts: 'क्लिनिकल कोहोर्ट रिकॉर्ड',

    totalExperiments: 'कुल विश्लेषण',
    activePatients: 'सक्रिय मरीज',
    avgViability: 'औसत व्यवहार्यता',
    isoPassRate: 'आईएसओ पास दर',
    recentActivity: 'हाल के नैदानिक परीक्षण',
    quickActions: 'त्वरित कार्य',
    startNewAssay: 'नया परीक्षण शुरू करें',
    enrollPatient: 'मरीज पंजीकृत करें',
    viewAllRecords: 'पूरा इतिहास देखें',

    step1Patient: '1. अध्ययन विषय / मरीज का चयन करें',
    step2Assay: '2. परीक्षण पैरामीटर और सेल मॉडल',
    step3Dose: '3. खुराक-प्रतिक्रिया माप (ऑप्टिकल घनत्व)',
    sampleTitle: 'नमूना / परीक्षण का नाम',
    targetCellLine: 'लक्षित सेल लाइन',
    exposureDuration: 'एक्सपोजर अवधि',
    biomedicalApp: 'बायोमेडिकल अनुप्रयोग लक्ष्य',
    calcCytotoxicity: 'आईएसओ 10993-5 विश्लेषण चलाएं',
    patientOptional: '👤 मरीज / विषय',
    generalScreening: '🔬 प्रीक्लिनिकल सामग्री स्क्रीनिंग (कोई मरीज नहीं)',
    enterCustomTitle: 'नमूना शीर्षक दर्ज करें...',
    evaluating: 'विश्लेषण चल रहा है...',
    concentration: 'सांद्रता (µg/mL)',
    opticalDensity: 'ऑप्टिकल घनत्व (OD 570nm)',
    blankControl: 'रिक्त नियंत्रण (Blank)',
    negativeControl: 'नकारात्मक नियंत्रण (100% व्यवहार्य)',

    analysisResult: 'विश्लेषण परिणाम',
    viabilityScore: 'सेल व्यवहार्यता',
    toxicityScore: 'विषाक्तता स्कोर',
    riskLevel: 'जोखिम स्तर',
    safe: 'सुरक्षित / बायोकम्पैटिबल',
    moderate: 'मध्यम जोखिम',
    toxic: 'उच्च जोखिम (विषाक्त)',
    ic50: 'गणना की गई IC50',
    conformance: 'आईएसओ 10993-5 अनुरूपता',
    isoPass: 'आईएसओ 10993-5 पास (व्यवहार्यता ≥ 70%)',
    isoFail: 'आईएसओ 10993-5 फेल (व्यवहार्यता < 70%)',
    dosageSafe: 'अनुशंसित सुरक्षित खुराक',
    reRunAssay: 'पुनः परीक्षण चलाएं',
    saveToHistory: 'इतिहास में सहेजें',

    allRecords: 'सभी रिकॉर्ड',
    patientAssays: 'मरीजों का इतिहास',
    materialScreening: 'सामग्री स्क्रीनिंग',
    showingAllPatients: 'दिखा रहा है: सभी पंजीकृत मरीज',
    searchHistory: 'मरीज, नमूना या सेल लाइन द्वारा खोजें...',
    filter: 'फ़िल्टर करें',
    reset: 'रीसेट',
    noRecords: 'कोई रिकॉर्ड नहीं मिला।',
    filterAll: 'सभी',
    filterSafe: 'सुरक्षित',
    filterModerate: 'मध्यम',
    filterToxic: 'विषाक्त',
    dateAdded: 'जोड़ने की तिथि',

    patientRegistry: 'क्लिनिकल स्टडी रजिस्ट्री',
    enrollNewPatient: 'नया मरीज नामांकित करें',
    patientName: 'मरीज का पूरा नाम',
    bloodGroup: 'रक्त समूह',
    cohort: 'अध्ययन समूह / कोहोर्ट',
    consentStatus: 'सहमति स्थिति',
    consented: 'सहमति प्राप्त',
    pending: 'लंबित',
    totalAssaysCount: 'रिकॉर्ड किए गए परीक्षण',
    enrollBtn: 'मरीज जोड़ें',
    patientId: 'मरीज आईडी',
    ageYears: 'आयु (वर्ष)',
    gender: 'लिंग',
    notes: 'नैदानिक विवरण / इतिहास',
    noPatientsFound: 'अभी तक कोई मरीज पंजीकृत नहीं है।',

    compareTitle: 'मल्टी-डेटासेट तुलना',
    compareSub: 'परीक्षणों के बीच खुराक-प्रतिक्रिया वक्रों और साइटोटॉक्सिसिटी की तुलना करें',
    selectDatasetA: 'डेटासेट A चुनें',
    selectDatasetB: 'डेटासेट B चुनें',
    deltaComparison: 'अंतर तुलना (Δ)',
    viabilityDiff: 'व्यवहार्यता अंतर',
    ic50Diff: 'IC50 अंतर',

    isoStandardsTitle: 'आईएसओ 10993-5 जैविक मूल्यांकन गाइड',
    isoGuideSub: 'चिकित्सा उपकरणों के साइटोटॉक्सिसिटी मूल्यांकन के अंतर्राष्ट्रीय मानक',
    grade0: 'ग्रेड 0: शून्य विषाक्तता (व्यवहार्यता ≥ 100%)',
    grade1: 'ग्रेड 1: मामूली (व्यवहार्यता 80% - 99%)',
    grade2: 'ग्रेड 2: हल्का (व्यवहार्यता 70% - 79%)',
    grade3: 'ग्रेड 3: मध्यम (व्यवहार्यता 50% - 69%)',
    grade4: 'ग्रेड 4: गंभीर (व्यवहार्यता < 50%)',
    isoPassThreshold: 'पास मानक: नकारात्मक नियंत्रण की तुलना में व्यवहार्यता ≥ 70%',

    researcherProfile: 'शोधकर्ता प्रोफ़ाइल',
    mandatoryInfo: '🔴 अनिवार्य जानकारी',
    optionalInfo: '⚪ वैकल्पिक जानकारी',
    saveProfile: 'शोधकर्ता प्रोफ़ाइल सहेजें',
    editProfile: 'प्रोफ़ाइल संपादित करें',
    identityDetails: '👤 पहचान और व्यक्तिगत विवरण',
    contactLocation: '📞 संपर्क और स्थान',
    labAffiliation: '🔬 प्रयोगशाला और संबद्धता',
    personalBio: '📝 व्यक्तिगत बायो / मेरे बारे में',
    fullName: 'पूरा कानूनी नाम',
    titleSalutation: 'शीर्षक / अभिवादन',
    institution: 'संस्थान / संगठन',
    researchRole: 'शोध भूमिका / पद',
    genderPronouns: 'लिंग / सर्वनाम',
    dateOfBirth: 'जन्म तिथि / आयु',
    primaryEmail: 'प्राथमिक ईमेल',
    secondaryEmail: 'वैकल्पिक / द्वितीयक ईमेल',
    officeAddress: 'कार्यालय / लैब का पता',
    cityState: 'शहर और राज्य',
    country: 'देश',
    preferredLanguage: 'पसंदीदा भाषा',
    bio: 'बायो / अनुसंधान सारांश',
    notSet: 'सेट नहीं है',
    verified: 'सत्यापित',
    uploadPhoto: 'फ़ोटो अपलोड करें',
    changePhoto: 'फ़ोटो बदलें',
    takePhoto: 'कैमरे से फ़ोटो लें',
    chooseGallery: 'गैलरी से चुनें',
    removePhoto: 'फ़ोटो हटाएं',
    cancel: 'रद्द करें',
    save: 'सहेजें',
    edit: 'संपादित करें',
    changePassword: 'पासवर्ड बदलें',
    security: 'सुरक्षा',
    currentPwd: 'वर्तमान पासवर्ड',
    newPwd: 'नया पासवर्ड',
    confirmPwd: 'नए पासवर्ड की पुष्टि करें',
    updatePassword: 'पासवर्ड अपडेट करें',

    signIn: 'साइन इन करें',
    register: 'खाता बनाएं',
    username: 'उपयोगकर्ता नाम',
    password: 'पासवर्ड',
    email: 'ईमेल पता',
    verifyOtp: '6-अंकीय ओटीपी सत्यापित करें',
    enterOtpCode: 'सत्यापन कोड दर्ज करें',
    verifyAndLogin: 'सत्यापित करें और आगे बढ़ें',
  },

  te: {
    // Telugu (తెలుగు)
    appName: 'నానోసేఫ్ ఎనలైజర్',
    appSub: 'నానోమెడిసిన్ మరియు సైటోటాక్సిసిటీ ప్లాట్‌ఫారమ్',
    projectTitle: 'సురక్షిత బయోమెడికల్ వినియోగ స్థాయిలను నిర్ణయించడానికి ZnO నానోపార్టికల్స్ బయోకంపాటిబిలిటీ మరియు సైటోటాక్సిసిటీ మూల్యాంకనం',
    dashboard: 'డాష్‌బోర్డ్',
    newAnalysis: 'కొత్త విశ్లేషణ',
    history: 'చరిత్ర',
    compare: 'పోల్చండి',
    patients: 'రోగులు / పేషెంట్లు',
    isoGuide: 'ISO ప్రమాణాలు',
    profile: 'ప్రొఫైల్',
    logout: 'లాగ్ అవుట్',
    changeLang: 'భాషను మార్చండి',
    selectLang: 'యాప్ భాషను ఎంచుకోండి',
    mlEngineActive: 'ML టాక్సికాలజీ ఇంజిన్ యాక్టివ్',
    welcomeBack: 'స్వాగతం,',
    quickModules: 'త్వరిత మాడ్యూల్స్',
    sideBySide: 'డేటాసెట్ పోలిక',
    pastRecords: 'గత పరీక్ష రికార్డులు',
    clinicalCohorts: 'క్లినికల్ కోహోర్ట్ రికార్డులు',

    totalExperiments: 'మొత్తం విశ్లేషణలు',
    activePatients: 'యాక్టివ్ పేషెంట్లు',
    avgViability: 'సగటు మనుగడ రేటు',
    isoPassRate: 'ISO పాస్ రేటు',
    recentActivity: 'ఇటీవలి క్లినికల్ పరీక్షలు',
    quickActions: 'త్వరిత చర్యలు',
    startNewAssay: 'కొత్త పరీక్ష ప్రారంభించండి',
    enrollPatient: 'రోగిని నమోదు చేయండి',
    viewAllRecords: 'మొత్తం చరిత్రను చూడండి',

    step1Patient: '1. రోగిని ఎంచుకోండి',
    step2Assay: '2. పరీక్ష పారామితులు మరియు కణ నమూనా',
    step3Dose: '3. డోస్ రెస్పాన్స్ కొలతలు (ఆప్టికల్ డెన్సిటీ)',
    sampleTitle: 'నమూనా / పరీక్ష పేరు',
    targetCellLine: 'టార్గెట్ సెల్ లైన్',
    exposureDuration: 'ఎక్స్‌పోజర్ సమయం',
    biomedicalApp: 'బయోమెడికల్ అప్లికేషన్ టార్గెట్',
    calcCytotoxicity: 'ISO 10993-5 విశ్లేషణను అమలు చేయండి',
    patientOptional: '👤 రోగి / పేషెంట్',
    generalScreening: '🔬 మెటీరియల్ స్క్రీనింగ్ (రోగి లేకుండా)',
    enterCustomTitle: 'నమూనా పేరు నమోదు చేయండి...',
    evaluating: 'విశ్లేషణ నడుస్తోంది...',
    concentration: 'గాఢత (µg/mL)',
    opticalDensity: 'ఆప్టికల్ డెన్సిటీ (OD 570nm)',
    blankControl: 'బ్లాంక్ కంట్రోల్',
    negativeControl: 'నెగటివ్ కంట్రోల్ (100% మనుగడ)',

    analysisResult: 'విశ్లేషణ ఫలితాలు',
    viabilityScore: 'కణ మనుగడ',
    toxicityScore: 'విషపూరిత స్కోరు',
    riskLevel: 'ప్రమాద స్థాయి',
    safe: 'సురక్షితమైనది / బయోకంపాటిబుల్',
    moderate: 'మధ్యస్థ ప్రమాదం',
    toxic: 'అధిక ప్రమాదం (విషపూరితం)',
    ic50: 'లెక్కించిన IC50',
    conformance: 'ISO 10993-5 అనుకూలత',
    isoPass: 'ISO 10993-5 పాస్ (మనుగడ ≥ 70%)',
    isoFail: 'ISO 10993-5 ఫెయిల్ (మనుగడ < 70%)',
    dosageSafe: 'సురక్షితమైన మోతాదు',
    reRunAssay: 'మళ్ళీ పరీక్షించండి',
    saveToHistory: 'చరిత్రలో భద్రపరచండి',

    allRecords: 'అన్ని రికార్డులు',
    patientAssays: 'రోగుల చరిత్ర',
    materialScreening: 'మెటీరియల్ స్క్రీనింగ్',
    showingAllPatients: 'చూపిస్తోంది: నమోదు చేసిన రోగులందరూ',
    searchHistory: 'పేషెంట్, నమూనా లేదా సెల్ లైన్ ద్వారా శోధించండి...',
    filter: 'ఫిల్టర్ చేయండి',
    reset: 'రీసెట్',
    noRecords: 'రికార్డులు కనుగొనబడలేదు.',
    filterAll: 'అన్నీ',
    filterSafe: 'సురక్షితం',
    filterModerate: 'మధ్యస్థం',
    filterToxic: 'విషపూరితం',
    dateAdded: 'తేదీ',

    patientRegistry: 'క్లినికల్ స్టడీ రిజిస్ట్రీ',
    enrollNewPatient: 'కొత్త రోగిని నమోదు చేయండి',
    patientName: 'రోగి పూర్తి పేరు',
    bloodGroup: 'రక్త వర్గం',
    cohort: 'స్టడీ గ్రూప్ / కోహోర్ట్',
    consentStatus: 'సమ్మతి స్థితి',
    consented: 'సమ్మతించారు',
    pending: 'పెండింగ్',
    totalAssaysCount: 'నమోదైన పరీక్షలు',
    enrollBtn: 'రోగిని నమోదు చేయండి',
    patientId: 'రోగి ID',
    ageYears: 'వయస్సు (సంవత్సరాలు)',
    gender: 'లింగం',
    notes: 'క్లినికల్ గమనికలు',
    noPatientsFound: 'ఇంకా రోగులు నమోదు కాలేదు.',

    compareTitle: 'బహుళ డేటాసెట్ పోలిక',
    compareSub: 'డోస్-రెస్పాన్స్ వక్రతలు మరియు విషపూరిత కొలతలను సరిపోల్చండి',
    selectDatasetA: 'డేటాసెట్ A ఎంచుకోండి',
    selectDatasetB: 'డేటాసెట్ B ఎంచుకోండి',
    deltaComparison: 'తేడా పోలిక (Δ)',
    viabilityDiff: 'మనుగడ తేడా',
    ic50Diff: 'IC50 తేడా',

    isoStandardsTitle: 'ISO 10993-5 బయోలాజికల్ ఎవాల్యుయేషన్ గైడ్',
    isoGuideSub: 'మెడికల్ పరికరాల సైటోటాక్సిసిటీ మూల్యాంకనం కొరకు అంతర్జాతీయ ప్రమాణాలు',
    grade0: 'గ్రేడ్ 0: శూన్యం (మనుగడ ≥ 100%)',
    grade1: 'గ్రేడ్ 1: కొద్దిగా (మనుగడ 80% - 99%)',
    grade2: 'గ్రేడ్ 2: తేలికపాటి (మనుగడ 70% - 79%)',
    grade3: 'గ్రేడ్ 3: మధ్యస్థం (మనుగడ 50% - 69%)',
    grade4: 'గ్రేడ్ 4: తీవ్రమైన (మనుగడ < 50%)',
    isoPassThreshold: 'పాస్ ప్రమాణం: కంట్రోల్ కంటే మనుగడ ≥ 70%',

    researcherProfile: 'పరిశోధకుడి ప్రొఫైల్',
    mandatoryInfo: '🔴 తప్పనిసరి సమాచారం',
    optionalInfo: '⚪ ఐచ్ఛిక సమాచారం',
    saveProfile: 'ప్రొఫైల్‌ను సేవ్ చేయండి',
    editProfile: 'ప్రొఫైల్‌ను సవరించండి',
    identityDetails: '👤 గుర్తింపు మరియు వ్యక్తిగత వివరాలు',
    contactLocation: '📞 సంప్రదింపు మరియు చిరునామా',
    labAffiliation: '🔬 ప్రయోగశాల & అనుబంధం',
    personalBio: '📝 వ్యక్తిగత బయో / నా గురించి',
    fullName: 'పూర్తి చట్టపరమైన పేరు',
    titleSalutation: 'శీర్షిక (డాక్టర్ / ప్రొఫెసర్)',
    institution: 'సంస్థ / విశ్వవిద్యాలయం',
    researchRole: 'పరిశోధన పాత్ర / హోదా',
    genderPronouns: 'లింగం',
    dateOfBirth: 'పుట్టిన తేదీ / వయస్సు',
    primaryEmail: 'ప్రధాన ఇమెయిల్',
    secondaryEmail: 'రెండవ ఇమెయిల్',
    officeAddress: 'కార్యాలయం / ల్యాబ్ చిరునామా',
    cityState: 'నగరం మరియు రాష్ట్రం',
    country: 'దేశం',
    preferredLanguage: 'ప్రాధాన్య భాష',
    bio: 'బయో / పరిశోధన సారాంశం',
    notSet: 'సెట్ చేయలేదు',
    verified: 'ధృవీకరించబడింది',
    uploadPhoto: 'ఫోటోను అప్‌లోడ్ చేయండి',
    changePhoto: 'ఫోటోను మార్చండి',
    takePhoto: 'కెమెరా ఫోటో తీయండి',
    chooseGallery: 'గ్యాలరీ నుండి ఎంచుకోండి',
    removePhoto: 'ఫోటోను తొలగించండి',
    cancel: 'రద్దు చేయండి',
    save: 'సేవ్ చేయండి',
    edit: 'సవరించండి',
    changePassword: 'పాస్‌వర్డ్‌ను మార్చండి',
    security: 'భద్రత',
    currentPwd: 'ప్రస్తుత పాస్‌వర్డ్',
    newPwd: 'కొత్త పాస్‌వర్డ్',
    confirmPwd: 'కొత్త పాస్‌వర్డ్‌ను నిర్ధారించండి',
    updatePassword: 'పాస్‌వర్డ్‌ను అప్‌డేట్ చేయండి',

    signIn: 'సైన్ ఇన్ చేయండి',
    register: 'ఖాతాను సృష్టించండి',
    username: 'వినియోగదారు పేరు',
    password: 'పాస్‌వర్డ్',
    email: 'ఇమెయిల్ చిరునామా',
    verifyOtp: '6-అంకెల OTP ని ధృవీకరించండి',
    enterOtpCode: 'ధృవీకరణ కోడ్‌ను నమోదు చేయండి',
    verifyAndLogin: 'ధృవీకరించి ప్రవేశించండి',
  },

  ta: {
    // Tamil (தமிழ்)
    appName: 'நானோசேஃப் ஆய்வாளர்',
    appSub: 'நானோமெடிசின் & சைட்டோடாக்சிசிட்டி தளம்',
    projectTitle: 'பாதுகாப்பான பயோமெடிக்கல் பயன்பாட்டு அளவை தீர்மானிக்க ZnO நானோ துகள்களின் சைட்டோடாக்சிசிட்டி மதிப்பீடு',
    dashboard: 'டாஷ்போர்டு',
    newAnalysis: 'புதிய பகுப்பாய்வு',
    history: 'வரலாறு',
    compare: 'ஒப்பிடுக',
    patients: 'நோயாளிகள்',
    isoGuide: 'ISO தரநிலைகள்',
    profile: 'சுயவிவரம்',
    logout: 'வெளியேறு',
    changeLang: 'மொழியை மாற்றவும்',
    selectLang: 'பயன்பாட்டு மொழியைத் தேர்ந்தெடுக்கவும்',
    mlEngineActive: 'ML நச்சுத்தன்மை இயந்திரம் இயங்குகிறது',
    welcomeBack: 'மீண்டும் வருக,',
    quickModules: 'விரைவு தொகுதிகள்',
    sideBySide: 'ஒப்பீட்டு தரவு',
    pastRecords: 'கடந்த பரிசோதனை பதிவுகள்',
    clinicalCohorts: 'மருத்துவ ஆய்வுக் குழு பதிவுகள்',

    totalExperiments: 'மொத்த பகுப்பாய்வுகள்',
    activePatients: 'செயலில் உள்ள நோயாளிகள்',
    avgViability: 'சராசரி செல் நம்பகத்தன்மை',
    isoPassRate: 'ISO தேர்ச்சி விகிதம்',
    recentActivity: 'சமீபத்திய மருத்துவ சோதனைகள்',
    quickActions: 'விரைவு செயல்கள்',
    startNewAssay: 'புதிய பரிசோதனையைத் தொடங்கு',
    enrollPatient: 'நோயாளியைப் பதிவு செய்க',
    viewAllRecords: 'முழு வரலாற்றையும் காண்க',

    step1Patient: '1. நோயாளியைத் தேர்ந்தெடுக்கவும்',
    step2Assay: '2. சோதனை அளவுருக்கள் மற்றும் செல் மாதிரி',
    step3Dose: '3. டோஸ் அளவீடுகள் (ஆப்டிகல் அடர்த்தி)',
    sampleTitle: 'மாதிரி / சோதனையின் பெயர்',
    targetCellLine: 'இலக்கு செல் வரிசை',
    exposureDuration: 'வெளிப்பாடு காலம்',
    biomedicalApp: 'பயோமெடிக்கல் பயன்பாடு',
    calcCytotoxicity: 'ISO 10993-5 பகுப்பாய்வை இயக்கு',
    patientOptional: '👤 நோயாளி',
    generalScreening: '🔬 பொருள் திரையிடல் (நோயாளி இல்லை)',
    enterCustomTitle: 'மாதிரி பெயரை உள்ளிடவும்...',
    evaluating: 'பகுப்பாய்வு இயங்குகிறது...',
    concentration: 'செறிவு (µg/mL)',
    opticalDensity: 'ஆப்டிகல் அடர்த்தி (OD 570nm)',
    blankControl: 'வெற்று கட்டுப்பாடு',
    negativeControl: 'எதிர்மறை கட்டுப்பாடு (100% நம்பகமானது)',

    analysisResult: 'பகுப்பாய்வு முடிவுகள்',
    viabilityScore: 'செல் நம்பகத்தன்மை',
    toxicityScore: 'நச்சுத்தன்மை மதிப்பெண்',
    riskLevel: 'ஆபத்து நிலை',
    safe: 'பாதுகாப்பானது / பயோ இணக்கமானது',
    moderate: 'மிதமான ஆபத்து',
    toxic: 'அதிக ஆபத்து (நச்சுத்தன்மை)',
    ic50: 'கணக்கிடப்பட்ட IC50',
    conformance: 'ISO 10993-5 இணக்கம்',
    isoPass: 'ISO 10993-5 தேர்ச்சி (நம்பகத்தன்மை ≥ 70%)',
    isoFail: 'ISO 10993-5 தோல்வி (நம்பகத்தன்மை < 70%)',
    dosageSafe: 'பரிந்துரைக்கப்பட்ட பாதுகாப்பான அளவு',
    reRunAssay: 'மீண்டும் சோதிக்கவும்',
    saveToHistory: 'வரலாற்றில் சேமிக்கவும்',

    allRecords: 'அனைத்து பதிவுகள்',
    patientAssays: 'நோயாளிகள் வரலாறு',
    materialScreening: 'பொருள் திரையிடல்',
    showingAllPatients: 'காண்பிக்கப்படுகிறது: பதிவு செய்யப்பட்ட அனைத்து நோயாளிகள்',
    searchHistory: 'நோயாளி அல்லது மாதிரி மூலம் தேடவும்...',
    filter: 'வடிகட்டு',
    reset: 'மீட்டமை',
    noRecords: 'பதிவுகள் எதுவும் இல்லை.',
    filterAll: 'அனைத்தும்',
    filterSafe: 'பாதுகாப்பானது',
    filterModerate: 'மிதமானது',
    filterToxic: 'நச்சுத்தன்மை',
    dateAdded: 'சேர்க்கப்பட்ட தேதி',

    patientRegistry: 'மருத்துவ ஆய்வு பதிவேடு',
    enrollNewPatient: 'புதிய நோயாளியைப் பதிவு செய்',
    patientName: 'நோயாளியின் முழுப் பெயர்',
    bloodGroup: 'இரத்த வகை',
    cohort: 'ஆய்வுக் குழு',
    consentStatus: 'ஒப்புதல் நிலை',
    consented: 'ஒப்புதல் அளிக்கப்பட்டது',
    pending: 'நிலுவையில் உள்ளது',
    totalAssaysCount: 'பதிவு செய்யப்பட்ட சோதனைகள்',
    enrollBtn: 'பதிவு செய்',
    patientId: 'நோயாளி ID',
    ageYears: 'வயது (ஆண்டுகள்)',
    gender: 'பாலினம்',
    notes: 'மருத்துவக் குறிப்புகள்',
    noPatientsFound: 'நோயாளிகள் யாரும் பதிவு செய்யப்படவில்லை.',

    compareTitle: 'பல தரவுத்தொகுப்பு ஒப்பீடு',
    compareSub: 'சோதனைகளில் டோஸ்-பதிலளிப்பு வளைவுகள் மற்றும் நச்சுத்தன்மை அளவீடுகளை ஒப்பிடுக',
    selectDatasetA: 'தரவுத்தொகுப்பு A தேர்ந்தெடுக்கவும்',
    selectDatasetB: 'தரவுத்தொகுப்பு B தேர்ந்தெடுக்கவும்',
    deltaComparison: 'வித்தியாச ஒப்பீடு (Δ)',
    viabilityDiff: 'நம்பகத்தன்மை வித்தியாசம்',
    ic50Diff: 'IC50 வித்தியாசம்',

    isoStandardsTitle: 'ISO 10993-5 உயிரியல் மதிப்பீட்டு வழிகாட்டி',
    isoGuideSub: 'மருத்துவ சாதனங்களின் சைட்டோடாக்சிசிட்டி மதிப்பீட்டிற்கான சர்வதேச தரநிலைகள்',
    grade0: 'கிரேடு 0: நச்சுத்தன்மை இல்லை (நம்பகத்தன்மை ≥ 100%)',
    grade1: 'கிரேடு 1: லேசானது (நம்பகத்தன்மை 80% - 99%)',
    grade2: 'கிரேடு 2: மிதமானது (நம்பகத்தன்மை 70% - 79%)',
    grade3: 'கிரேடு 3: நடுத்தரமானது (நம்பகத்தன்மை 50% - 69%)',
    grade4: 'கிரேடு 4: கடுமையானது (நம்பகத்தன்மை < 50%)',
    isoPassThreshold: 'தேர்ச்சி தரம்: கட்டுப்பாட்டுடன் ஒப்பிடும்போது நம்பகத்தன்மை ≥ 70%',

    researcherProfile: 'ஆராய்ச்சியாளர் சுயவிவரம்',
    mandatoryInfo: '🔴 கட்டாய தகவல்',
    optionalInfo: '⚪ விருப்ப தகவல்',
    saveProfile: 'சுயவிவரத்தைச் சேமிக்கவும்',
    editProfile: 'சுயவிவரத்தைத் திருத்து',
    identityDetails: '👤 அடையாளம் மற்றும் தனிப்பட்ட விவரங்கள்',
    contactLocation: '📞 தொடர்பு மற்றும் இருப்பிடம்',
    labAffiliation: '🔬 ஆய்வகம் மற்றும் இணைப்பு',
    personalBio: '📝 சுய குறிப்பு / என்னைப் பற்றி',
    fullName: 'முழு சட்டப் பெயர்',
    titleSalutation: 'தலைப்பு (Dr. / Prof.)',
    institution: 'நிறுவனம் / பல்கலைக்கழகம்',
    researchRole: 'ஆராய்ச்சிப் பங்கு / பதவி',
    genderPronouns: 'பாலினம்',
    dateOfBirth: 'பிறந்த தேதி / வயது',
    primaryEmail: 'முதன்மை மின்னஞ்சல்',
    secondaryEmail: 'மாற்று மின்னஞ்சல்',
    officeAddress: 'அலுவலகம் / ஆய்வக முகவரி',
    cityState: 'நகரம் மற்றும் மாநிலம்',
    country: 'நாடு',
    preferredLanguage: 'விருப்பமான மொழி',
    bio: 'ஆராய்ச்சி சுருக்கம்',
    notSet: 'அமைக்கப்படவில்லை',
    verified: 'சரிபார்க்கப்பட்டது',
    uploadPhoto: 'புகைப்படத்தைப் பதிவேற்று',
    changePhoto: 'புகைப்படத்தை மாற்றவும்',
    takePhoto: 'புகைப்படம் எடுக்கவும்',
    chooseGallery: 'கேலரியில் இருந்து தேர்வு செய்',
    removePhoto: 'புகைப்படத்தை அகற்று',
    cancel: 'ரத்துசெய்',
    save: 'சேமிக்க',
    edit: 'திருத்து',
    changePassword: 'கடவுச்சொல்லை மாற்றவும்',
    security: 'பாதுகாப்பு',
    currentPwd: 'தற்போதைய கடவுச்சொல்',
    newPwd: 'புதிய கடவுச்சொல்',
    confirmPwd: 'புதிய கடவுச்சொல்லை உறுதிப்படுத்தவும்',
    updatePassword: 'கடவுச்சொல்லைப் புதுப்பிக்கவும்',

    signIn: 'உள்நுழைக',
    register: 'கணக்கை உருவாக்கவும்',
    username: 'பயனர்பெயர்',
    password: 'கடவுச்சொல்',
    email: 'மின்னஞ்சல் முகவரி',
    verifyOtp: '6 இலக்க OTP ஐ சரிபார்க்கவும்',
    enterOtpCode: 'சரிபார்ப்புக் குறியீட்டை உள்ளிடவும்',
    verifyAndLogin: 'சரிபார்த்து தொடரவும்',
  },

  es: {
    appName: 'NanoSafe Analyzer',
    appSub: 'Plataforma de Nanomedicina y Citotoxicidad',
    projectTitle: 'Evaluación de la Biocompatibilidad y Citotoxicidad de Nanopartículas de ZnO para Determinar Niveles Seguros',
    dashboard: 'Panel de Control',
    newAnalysis: 'Nuevo Análisis',
    history: 'Historial',
    compare: 'Comparar',
    patients: 'Pacientes',
    isoGuide: 'Normas ISO',
    profile: 'Perfil',
    logout: 'Cerrar Sesión',
    changeLang: 'Cambiar Idioma',
    selectLang: 'Seleccionar Idioma',
    welcomeBack: 'Bienvenido,',
    quickModules: 'Módulos de Acceso Rápido',
    totalExperiments: 'Análisis Totales',
    activePatients: 'Pacientes Activos',
    avgViability: 'Viabilidad Promedio',
    isoPassRate: 'Tasa Aprobación ISO',
    recentActivity: 'Ensayos Clínicos Recientes',
    quickActions: 'Acciones Rápidas',
    startNewAssay: 'Iniciar Nuevo Ensayo',
    enrollPatient: 'Inscribir Paciente',
    viewAllRecords: 'Ver Todo el Historial',
    step1Patient: '1. Seleccionar Sujeto / Paciente',
    step2Assay: '2. Parámetros del Ensayo y Modelo Celular',
    step3Dose: '3. Mediciones Dosis-Respuesta (DO 570nm)',
    calcCytotoxicity: 'Ejecutar Análisis ISO 10993-5',
    viabilityScore: 'Viabilidad Celular',
    toxicityScore: 'Puntuación de Toxicidad',
    riskLevel: 'Nivel de Riesgo',
    safe: 'Seguro / Biocompatible',
    moderate: 'Riesgo Moderado',
    toxic: 'Alto Riesgo (Citotóxico)',
    ic50: 'IC50 Calculado',
    allRecords: 'Todos los Registros',
    patientAssays: 'Historial de Pacientes',
    materialScreening: 'Pruebas de Materiales',
    patientRegistry: 'Registro de Pacientes',
    enrollNewPatient: 'Inscribir Paciente',
    researcherProfile: 'Perfil del Investigador',
    mandatoryInfo: '🔴 Información Obligatoria',
    optionalInfo: '⚪ Información Opcional',
    saveProfile: 'Guardar Perfil',
    editProfile: 'Editar Perfil',
    fullName: 'Nombre Legal Completo',
    institution: 'Institución / Organización',
    researchRole: 'Rol de Investigación',
    notSet: 'No establecido',
    verified: 'Verificado',
    uploadPhoto: 'Subir Foto',
    cancel: 'Cancelar',
    save: 'Guardar',
    edit: 'Editar',
    changePassword: 'Cambiar Contraseña',
    security: 'Seguridad',
  },

  fr: {
    appName: 'NanoSafe Analyzer',
    appSub: 'Plateforme de Nanomédecine et Cytotoxicité',
    projectTitle: 'Évaluation de la Biocompatibilité et de la Cytotoxicité des Nanoparticules de ZnO',
    dashboard: 'Tableau de Bord',
    newAnalysis: 'Nouvelle Analyse',
    history: 'Historique',
    compare: 'Comparer',
    patients: 'Patients',
    isoGuide: 'Normes ISO',
    profile: 'Profil',
    logout: 'Déconnexion',
    changeLang: 'Changer de Langue',
    selectLang: 'Choisir la Langue',
    welcomeBack: 'Bienvenue,',
    quickModules: 'Modules Rapides',
    totalExperiments: 'Analyses Totales',
    activePatients: 'Patients Actifs',
    avgViability: 'Viabilité Moyenne',
    isoPassRate: 'Taux Réussite ISO',
    recentActivity: 'Essais Cliniques Récents',
    quickActions: 'Actions Rapides',
    startNewAssay: 'Nouvel Essai',
    enrollPatient: 'Inscrire un Patient',
    viewAllRecords: "Voir Tout l'Historique",
    step1Patient: '1. Sélectionner le Sujet / Patient',
    step2Assay: '2. Paramètres et Modèle Cellulaire',
    step3Dose: '3. Mesures Dose-Réponse (DO 570nm)',
    calcCytotoxicity: 'Exécuter Analyse ISO 10993-5',
    viabilityScore: 'Viabilité Cellulaire',
    toxicityScore: 'Score de Toxicité',
    riskLevel: 'Niveau de Risque',
    safe: 'Sûr / Biocompatible',
    moderate: 'Risque Modéré',
    toxic: 'Risque Élevé (Toxique)',
    ic50: 'IC50 Calculé',
    allRecords: 'Tous les Dossiers',
    patientAssays: 'Historique Patients',
    materialScreening: 'Criblage Matériaux',
    patientRegistry: 'Registre des Patients',
    enrollNewPatient: 'Inscrire un Patient',
    researcherProfile: 'Profil du Chercheur',
    mandatoryInfo: '🔴 Informations Obligatoires',
    optionalInfo: '⚪ Informations Optionnelles',
    saveProfile: 'Enregistrer le Profil',
    editProfile: 'Modifier le Profil',
    fullName: 'Nom Légal Complet',
    institution: 'Institution / Organisation',
    researchRole: 'Rôle de Recherche',
    notSet: 'Non défini',
    verified: 'Vérifié',
    uploadPhoto: 'Télécharger Photo',
    cancel: 'Annuler',
    save: 'Enregistrer',
    edit: 'Modifier',
    changePassword: 'Changer le Mot de Passe',
    security: 'Sécurité',
  },

  de: {
    appName: 'NanoSafe Analyzer',
    appSub: 'Plattform für Nanomedizin und Zytotoxizität',
    projectTitle: 'Bewertung der Biokompatibilität und Zytotoxizität von ZnO-Nanopartikeln',
    dashboard: 'Übersicht',
    newAnalysis: 'Neue Analyse',
    history: 'Verlauf',
    compare: 'Vergleichen',
    patients: 'Patienten',
    isoGuide: 'ISO-Normen',
    profile: 'Profil',
    logout: 'Abmelden',
    changeLang: 'Sprache Ändern',
    selectLang: 'Sprache Auswählen',
    welcomeBack: 'Willkommen,',
    quickModules: 'Schnellzugriff-Module',
    totalExperiments: 'Gesamtanalysen',
    activePatients: 'Aktive Patienten',
    avgViability: 'Durchschnittl. Viabilität',
    isoPassRate: 'ISO-Bestehensrate',
    recentActivity: 'Neueste Klinische Tests',
    quickActions: 'Schnellaktionen',
    startNewAssay: 'Neuen Test Starten',
    enrollPatient: 'Patient Einschreiben',
    viewAllRecords: 'Gesamten Verlauf Anzeigen',
    step1Patient: '1. Patient / Proband Wählen',
    step2Assay: '2. Testparameter & Zellmodell',
    step3Dose: '3. Dosis-Wirkungs-Messungen (OD 570nm)',
    calcCytotoxicity: 'ISO 10993-5 Analyse Starten',
    viabilityScore: 'Zellviabilität',
    toxicityScore: 'Toxizitätswert',
    riskLevel: 'Risikostufe',
    safe: 'Sicher / Biokompatibel',
    moderate: 'Mäßiges Risiko',
    toxic: 'Hohes Risiko (Toxisch)',
    ic50: 'Berechneter IC50',
    allRecords: 'Alle Datensätze',
    patientAssays: 'Patientenverlauf',
    materialScreening: 'Materialprüfung',
    patientRegistry: 'Patientenregister',
    enrollNewPatient: 'Patient Einschreiben',
    researcherProfile: 'Forscherprofil',
    mandatoryInfo: '🔴 Pflichtangaben',
    optionalInfo: '⚪ Optionale Angaben',
    saveProfile: 'Profil Speichern',
    editProfile: 'Profil Bearbeiten',
    fullName: 'Vollständiger Name',
    institution: 'Institution / Organisation',
    researchRole: 'Forschungsrolle',
    notSet: 'Nicht angegeben',
    verified: 'Verifiziert',
    uploadPhoto: 'Foto Hochladen',
    cancel: 'Abbrechen',
    save: 'Speichern',
    edit: 'Bearbeiten',
    changePassword: 'Passwort Ändern',
    security: 'Sicherheit',
  },

  ja: {
    appName: 'NanoSafe アナライザー',
    appSub: 'ナノ医療・細胞毒性評価プラットフォーム',
    projectTitle: '安全な医療応用のための酸化亜鉛ナノ粒子の生体適合性および細胞毒性評価',
    dashboard: 'ダッシュボード',
    newAnalysis: '新規分析',
    history: '履歴',
    compare: '比較',
    patients: '患者',
    isoGuide: 'ISO規格',
    profile: 'プロフィール',
    logout: 'ログアウト',
    changeLang: '言語を変更',
    selectLang: '言語を選択',
    welcomeBack: 'お帰りなさい、',
    quickModules: 'クイックアクセス',
    totalExperiments: '総分析数',
    activePatients: '登録患者数',
    avgViability: '平均細胞生存率',
    isoPassRate: 'ISO適合率',
    recentActivity: '最近の臨床試験',
    quickActions: 'クイックアクション',
    startNewAssay: '新規試験を開始',
    enrollPatient: '患者を登録',
    viewAllRecords: '全履歴を表示',
    step1Patient: '1. 対象患者を選択',
    step2Assay: '2. 試験条件と細胞モデル',
    step3Dose: '3. 用量反応測定 (OD 570nm)',
    calcCytotoxicity: 'ISO 10993-5 分析を実行',
    viabilityScore: '細胞生存率',
    toxicityScore: '毒性スコア',
    riskLevel: 'リスクレベル',
    safe: '安全 / 生体適合性あり',
    moderate: '中程度のリスク',
    toxic: '高リスク（細胞毒性）',
    ic50: '算出されたIC50',
    allRecords: '全記録',
    patientAssays: '患者履歴',
    materialScreening: '材料スクリーニング',
    patientRegistry: '臨床患者レジストリ',
    enrollNewPatient: '患者を登録',
    researcherProfile: '研究者プロフィール',
    mandatoryInfo: '🔴 必須情報',
    optionalInfo: '⚪ 任意情報',
    saveProfile: 'プロフィールを保存',
    editProfile: 'プロフィールを編集',
    fullName: '氏名（本名）',
    institution: '所属機関',
    researchRole: '役職 / 肩書',
    notSet: '未設定',
    verified: '認証済み',
    uploadPhoto: '写真をアップロード',
    cancel: 'キャンセル',
    save: '保存',
    edit: '編集',
    changePassword: 'パスワード変更',
    security: 'セキュリティ',
  },

  ar: {
    appName: 'محلل نانوسيف',
    appSub: 'منصة طب النانو والسمية الخلوية',
    projectTitle: 'تقييم التوافق الحيوي والسمية الخلوية لجسيمات أكسيد الزنك النانوية',
    dashboard: 'لوحة القيادة',
    newAnalysis: 'تحليل جديد',
    history: 'السجل',
    compare: 'مقارنة',
    patients: 'المرضى',
    isoGuide: 'معايير ISO',
    profile: 'الملف الشخصي',
    logout: 'تسجيل الخروج',
    changeLang: 'تغيير اللغة',
    selectLang: 'اختر اللغة',
    welcomeBack: 'مرحباً بعودتك،',
    quickModules: 'وحدات الوصول السريع',
    totalExperiments: 'إجمالي التحليلات',
    activePatients: 'المرضى النشطون',
    avgViability: 'متوسط الحيوية',
    isoPassRate: 'معدل اجتياز ISO',
    recentActivity: 'التجارب السريرية الأخيرة',
    quickActions: 'إجراءات سريعة',
    startNewAssay: 'بدء فحص جديد',
    enrollPatient: 'تسجيل مريض',
    viewAllRecords: 'عرض كل السجل',
    step1Patient: '1. اختر المريض / العينة',
    step2Assay: '2. معايير الفحص والنموذج الخلوي',
    step3Dose: '3. قياسات الجرعة والاستجابة (OD 570nm)',
    calcCytotoxicity: 'تشغيل تحليل ISO 10993-5',
    viabilityScore: 'حيوية الخلايا',
    toxicityScore: 'درجة السمية',
    riskLevel: 'مستوى الخطورة',
    safe: 'آمن / متوافق حيوياً',
    moderate: 'خطر متوسط',
    toxic: 'خطر عالي (سام خلوياً)',
    ic50: 'IC50 المحسوب',
    allRecords: 'كل السجلات',
    patientAssays: 'سجل المرضى',
    materialScreening: 'فحص المواد',
    patientRegistry: 'سجل المرضى السريري',
    enrollNewPatient: 'تسجيل مريض',
    researcherProfile: 'ملف الباحث',
    mandatoryInfo: '🔴 معلومات إلزامية',
    optionalInfo: '⚪ معلومات اختيارية',
    saveProfile: 'حفظ الملف الشخصي',
    editProfile: 'تعديل الملف الشخصي',
    fullName: 'الاسم الكامل',
    institution: 'المؤسسة',
    researchRole: 'الدور البحثي',
    notSet: 'غير محدد',
    verified: 'تم التحقق',
    uploadPhoto: 'تحميل صورة',
    cancel: 'إلغاء',
    save: 'حفظ',
    edit: 'تعديل',
    changePassword: 'تغيير كلمة المرور',
    security: 'الأمان',
  }
};

const LANG_STORAGE_KEY = 'nanosafe_app_language_code';

export const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [currentLang, setCurrentLang] = useState('en');
  const [showLanguageModal, setShowLanguageModal] = useState(false);

  useEffect(() => {
    loadSavedLanguage();
  }, []);

  const loadSavedLanguage = async () => {
    try {
      const saved = await AsyncStorage.getItem(LANG_STORAGE_KEY);
      if (saved && TRANSLATIONS[saved]) {
        setCurrentLang(saved);
      }
    } catch (e) {
      console.log('Failed to load language setting:', e);
    }
  };

  const changeLanguage = async (langCode) => {
    if (TRANSLATIONS[langCode]) {
      setCurrentLang(langCode);
      try {
        await AsyncStorage.setItem(LANG_STORAGE_KEY, langCode);
      } catch (e) {
        console.log('Failed to save language:', e);
      }
      setShowLanguageModal(false);
    }
  };

  // Translation helper function
  const t = (key, fallback = '') => {
    const langDict = TRANSLATIONS[currentLang] || TRANSLATIONS.en;
    if (langDict && langDict[key] !== undefined) {
      return langDict[key];
    }
    // Fallback to English
    if (TRANSLATIONS.en && TRANSLATIONS.en[key] !== undefined) {
      return TRANSLATIONS.en[key];
    }
    return fallback || key;
  };

  const currentLangObj = SUPPORTED_LANGUAGES.find(l => l.code === currentLang) || SUPPORTED_LANGUAGES[0];

  return (
    <LanguageContext.Provider value={{
      currentLang,
      currentLangObj,
      languages: SUPPORTED_LANGUAGES,
      changeLanguage,
      t,
      showLanguageModal,
      setShowLanguageModal,
    }}>
      {children}
    </LanguageContext.Provider>
  );
};
